[alias]
lint = "clippy -- -A clippy::needless_arbitrary_self_type -A clippy::len_without_is_empty"
plint = "clippy -- -D clippy::pedantic -A clippy::needless_arbitrary_self_type -A clippy::missing_errors_doc -A clippy::len_without_is_empty -A clippy::module_name_repetitions"
